title: Hem
views:
  - path: default_view
    title: Dashboard
    icon: mdi:view-dashboard-variant-outline
    grid_gap: 10
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
        - type: weather-forecast
          entity: weather.smhi_home
        - type: horizontal-stack
          cards:
            - type: sensor
              graph: line
              entity: sensor.temperature_14
              name: Sovrum
            - type: sensor
              entity: sensor.kontor_temperatur_sensor
              graph: line
              name: Kontor
        - type: horizontal-stack
          cards:
            - type: picture
              image: 'http://homeassistant.local:8081'
              tap_action:
                action: none
              hold_action:
                action: none  
            - type: picture
              image: 'http://homeassistant.local:8083'
              tap_action:
                action: none
              hold_action:
                action: none  
        - break
        - type: entities
          entities:
            - type: custom:slider-entity-row
              toggle: true
              entity: light.dimmable_light_13_i5
              name: Taklampa
            - type: custom:slider-entity-row
              toggle: true
              entity: light.color_temperature_light_9
              name: Lindas lampa
            - type: custom:slider-entity-row
              toggle: true
              entity: light.color_temperature_light_10
              name: Johans lampa  
          title: Sovrum
        - type: entities
          entities:
            - type: custom:slider-entity-row
              toggle: true
              entity: light.office_ceiling
              name: Taklampa
            - type: custom:slider-entity-row
              toggle: true
              entity: light.color_temperature_light_7
              name: Skrivbordslampa
          title: Kontor
        - type:  entities
          entities:
            - type: custom:slider-entity-row
              toggle: true
              entity: light.dimmable_light_5
              name: Taklampa (norra)
            - type: custom:slider-entity-row
              toggle: true
              entity: light.dimmable_light_4
              name: Taklampa (södra)
          title: Hall (nya delen)
        - break
        - type: entities
          entities:
            - type: custom:slider-entity-row
              toggle: true
              entity: light.color_light_16
              name: Taklampa
          title: Elsies rum
        - type: entities
          entities:
            - type: custom:slider-entity-row
              toggle: true
              entity: light.color_light_16
              name: Taklampa
          title: Jacobs rum
        - type: custom:mini-media-player
          entity: media_player.kok
          info: short
          artwork: cover
          hide:
            power: true
            icon: true
            source: true
          speaker_group:
            platform: sonos
            show_group_count: true
            entities:
              - entity_id: media_player.kok
                name: Sonos Kök
              - entity_id: media_player.bibliotek
                name: Sonos Biblotek
              - entity_id: media_player.vardagsrum
                name: Sonos Vardagsrum
  - path: bedroom
    title: Beddroom
    panel: true
    icon: mdi:bed
    cards:
      - type: entities
        entities:
          - entity: input_boolean.bedroom_disable_timer
  - path: system
    title: System
    panel: true
    icon: mdi:raspberry-pi
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: Lights on
              show_header_toggle: false
            filter:
              include:
                - domain: light
              exclude:
              - state: "unavailable"              
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: Lights on
              show_header_toggle: false
            filter:
              include:
                - domain: light
                  state: "unavailable"

    